### ISSUE TITLE
'ReferenceError: ClassyTestCase is not defined' with Meteor 1.4.3.2

### ISSUE THREAD

**Issue by CristianoGil** [peerlibrary/meteor-classy-test#13]
I did update the **Meteor**, from version **1.4.3.1** to version **1.4.3.2** and then I had this on console error:

```
W20170321-12:34:45.576(2)? (STDERR) /home/anm-linux/.meteor/packages/meteor-tool/.1.4.3_2.1vx7kvy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170321-12:34:45.577(2)? (STDERR) 						throw(ex);
W20170321-12:34:45.577(2)? (STDERR) 						^
W20170321-12:34:45.577(2)? (STDERR) 
W20170321-12:34:45.578(2)? (STDERR) ReferenceError: ClassyTestCase is not defined
W20170321-12:34:45.578(2)? (STDERR)     at packages/peerlibrary_user-extra.js:218:4
W20170321-12:34:45.578(2)? (STDERR)     at packages/peerlibrary_user-extra.js:224:4
W20170321-12:34:45.578(2)? (STDERR)     at packages/peerlibrary_user-extra.js:231:3
W20170321-12:34:45.579(2)? (STDERR)     at /home/anm-linux/urbanaMapasBuild/ubi-mapas/.meteor/local/build/programs/server/boot.js:303:34
W20170321-12:34:45.579(2)? (STDERR)     at Array.forEach (native)
W20170321-12:34:45.579(2)? (STDERR)     at Function._.each._.forEach (/home/anm-linux/.meteor/packages/meteor-tool/.1.4.3_2.1vx7kvy++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170321-12:34:45.579(2)? (STDERR)     at /home/anm-linux/urbanaMapasBuild/ubi-mapas/.meteor/local/build/programs/server/boot.js:128:5
W20170321-12:34:45.580(2)? (STDERR)     at /home/anm-linux/urbanaMapasBuild/ubi-mapas/.meteor/local/build/programs/server/boot.js:352:5
W20170321-12:34:45.580(2)? (STDERR)     at Function.run (/home/anm-linux/urbanaMapasBuild/ubi-mapas/.meteor/local/build/programs/server/profile.js:510:12)
W20170321-12:34:45.580(2)? (STDERR)     at /home/anm-linux/urbanaMapasBuild/ubi-mapas/.meteor/local/build/programs/server/boot.js:351:11
```
And I have these packages installed in my project:

```
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.3
allow-deny@1.0.5
anback:bootstrap-validator@0.9.0
anti:fake@0.4.1
autoupdate@1.3.12
babel-compiler@6.14.1
babel-runtime@1.0.1
base64@1.0.10
bigdsk:inputmask@3.3.3
binary-heap@1.0.10
blaze@2.3.0
blaze-html-templates@1.1.0
blaze-tools@1.0.10
boilerplate-generator@1.0.11
caching-compiler@1.1.9
caching-html-compiler@1.1.0
callback-hook@1.0.10
check@1.2.5
coffeescript@1.12.3_1
cristiano:reactive-animation@0.0.1
ddp@1.2.5
ddp-client@1.3.3
ddp-common@1.2.8
ddp-rate-limiter@1.0.6
ddp-server@1.3.13
deps@1.0.12
diff-sequence@1.0.7
easy:search@2.1.6
easysearch:components@2.1.5
easysearch:core@2.1.6
ecmascript@0.6.3
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.1.18
es5-shim@4.6.15
fastclick@1.0.13
fezvrasta:bootstrap-material-design@0.5.9
fortawesome:fontawesome@4.7.0
geojson-utils@1.0.10
hinas:meteor-bootstrap-confirmation@0.9.0
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.11
id-map@1.0.9
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.1.0
iron:router@1.1.2
iron:url@1.1.0
jquery@1.11.10
jss:pace@1.0.0
launch-screen@1.1.1
less@2.7.9
livedata@1.0.18
localstorage@1.0.12
logging@1.1.17
mdg:validated-method@1.1.0
mdg:validation-error@0.5.1
meteor@1.6.1
meteor-base@1.0.4
minifier-css@1.2.16
minifier-js@1.2.18
minimongo@1.0.20
mobile-experience@1.0.4
mobile-status-bar@1.0.14
modules@0.7.9
modules-runtime@0.7.9
momentjs:moment@2.17.1
mongo@1.1.15
mongo-id@1.0.6
npm-bcrypt@0.9.2
npm-mongo@2.2.16_1
observe-sequence@1.0.15
ordered-dict@1.0.9
peerlibrary:assert@0.2.5
peerlibrary:base-component@0.16.0
peerlibrary:blaze-components@0.21.0
peerlibrary:computed-field@0.6.1
peerlibrary:data-lookup@0.1.0
peerlibrary:reactive-field@0.3.0
percolate:synced-cron@1.3.2
practicalmeteor:chai@2.1.0_1
promise@0.8.8
raix:eventemitter@0.1.3
raix:handlebar-helpers@0.2.5
random@1.0.10
rate-limit@1.0.6
reactive-dict@1.1.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
semantic:ui-css-local@2.2.7
semantic:ui-dropdown@2.1.7
semantic:ui-transition@2.1.7
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.2
spacebars@1.0.13
spacebars-compiler@1.1.0
srp@1.0.10
standard-minifier-css@1.3.4
standard-minifier-js@1.2.3
templating@1.3.0
templating-compiler@1.3.0
templating-runtime@1.3.0
templating-tools@1.1.0
themeteorchef:jquery-validation@1.14.0
tracker@1.1.2
twbs:bootstrap@3.3.6
ui@1.0.12
underscore@1.0.10
url@1.1.0
velocityjs:velocityjs@1.2.1
vsivsi:file-collection@1.3.7
webapp@1.3.13
webapp-hashing@1.0.9
zimme:bootstrap-hover-dropdown@2.1.3
```

**Comment by mitar** [comment]
Hm, the error is coming from `user-extra` package, but you do not have it listed in your list of packages?

Anyway, try to upgrade `user-extra` package to 0.1.2 version.

**Comment by CristianoGil** [comment]
Unfortunately it does not work. However thanks.

**Comment by mitar** [comment]
Can you create a small reproduction?

**Comment by CristianoGil** [comment]
I'm feeling ignorant. but what is **"create a small reproduction"** and how i can do?

**Comment by mitar** [comment]
Reproduction is to create a small GitHub repository with Meteor app which is the minimal possible app exhibiting your issue. So in this case, make the smallest possible app which is failing with the error above. By making that, I can then easier debug what is wrong and help you.

**Comment by CristianoGil** [comment]
Roger that. Thanks.

**Comment by CristianoGil** [comment]
I finally got the error resolved. 

I simply removed the following packages: **peerlibrary:classy-test**, **peerlibrary:user-extra** , **tinytes**t and   **peerlibrary:publish-context**. And the last two were automatically removed.

**Comment by mitar** [comment]
OK, but this does not explain why it does not work. can you create a reproduction?

**Comment by mitar** [comment]
This is in fact a strange error with Meteor: https://github.com/meteor/meteor/issues/8512

Closing in favor of: https://github.com/peerlibrary/meteor-user-extra/issues/1
